---
- name: First Play - Docker Image Build
  hosts: docker
  tasks:
    - name: Copy Dockerfile
      copy:
        src: Dockerfile
        dest: /home/ansible/

    - name: Copy Artifact
      copy:
        src: target
        dest: /home/ansible

    - name: Build image
      command: docker build -t hunjan/mavenwebapp .

    - name: Docker Hub login
      command: docker login -u "{{ docker_hub_username }}" -p "{{ docker_hub_password }}"

    - name: Push Docker Image
      command: docker push hunjan/mavenwebapp

- name: Second Play - K8s Deployment
  hosts: eks
  tasks:
    - name: Copy k8s-deploy.yml
      copy:
        src: k8s-deploy.yml
        dest: /home/ansible

    - name: K8S Deployment
      command: kubectl apply -f k8s-deploy.yml
