---
- name: First Play - Docker Image Build
  hosts: docker
  tasks:
    - name: Copy Dockerfile
      copy:
       src: Dockerfile
       dest: /home/ansible/
    - name: Copy Artifact
      copy:
       src: target
       dest: /home/ansible
    - name : Build image
      command: sudo docker build -t hunjan/mavenwebapp .
    - name : sudo Push Docker Image
      command: sudo docker push hunjan/mavenwebapp
- name: Second Play - K8s Deployment
  hosts: eks
  tasks:
   - name: 
     copy:
       src: k8s-deploy.yml
       dest: /home/ansadmin
   - name : K8S Deployment
     command: kubectl apply -f k8s-deploy.yml
